/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GROUP_PROJECT;


import static java.lang.System.exit;
import javax.swing.JOptionPane;

import com.mysql.cj.xdevapi.Statement;
import static java.lang.System.exit;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author JK
 */
public class NEW_V extends javax.swing.JFrame {
    
 
    
    
    public NEW_V() {
        initComponents();
        Select();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Birth = new javax.swing.JTextField();
        Gender = new javax.swing.JComboBox<>();
        Contact = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Status = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Place = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        muni = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        street = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Suffix = new javax.swing.JComboBox<>();
        sta = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        No = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GROUP_PROJECT/2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -20, 100, 140));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Full Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Date of birth");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contact information");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Current Address:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Citizenship Status");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        Name.setBackground(new java.awt.Color(255, 255, 255));
        Name.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 220, 30));

        Birth.setBackground(new java.awt.Color(255, 255, 255));
        Birth.setForeground(new java.awt.Color(0, 0, 0));
        Birth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthActionPerformed(evt);
            }
        });
        jPanel1.add(Birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 210, 30));

        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Male", "Female" }));
        jPanel1.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 100, 30));

        Contact.setBackground(new java.awt.Color(255, 255, 255));
        Contact.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 190, 30));

        Address.setBackground(new java.awt.Color(255, 255, 255));
        Address.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 210, 30));

        Status.setBackground(new java.awt.Color(255, 255, 255));
        Status.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 200, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FullName", "Birthday", "Gender", "Contact", "Province", "City/Municipal", "House.No", "Citizenship", "Place of birth", "Age", "Civil Status", "Suffix", "Rno"
            }
        ));
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1150, 470));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, -1, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("New Voters Information");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("CLEAR\n");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 90, 40));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 80, 40));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, 40));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 571, 90, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 1180, 620));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Republic of the Philippines");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 204, 255));
        jLabel10.setText("Commission of Election");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Place of Birth");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        Place.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Place, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 230, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Civil Status");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Province");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("City/Municipallity");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        muni.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(muni, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 210, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("House No./Street\n");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        street.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 210, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 380, 130));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Age");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        Age.setBackground(new java.awt.Color(255, 255, 255));
        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });
        jPanel1.add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 190, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Suffix");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, -1, -1));

        Suffix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "None", "Jr", "Sr", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "VIIII", "X" }));
        jPanel1.add(Suffix, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 672, 100, 30));

        sta.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 622, 170, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Registration no:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, -1, -1));

        No.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(No, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 732, 200, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1670, 786));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
          int result = JOptionPane.showOptionDialog(null, "Do you want to Exit?", "Confirmation",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

       if(result == JOptionPane.YES_OPTION){
           exit(0);
       }else if(result == JOptionPane.NO_OPTION){
          JOptionPane.showMessageDialog(null, "Proceed Again Ms and Mr", "Read-Only Dialog", JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Name.setText("");
           Birth.setText("");
           //gender
           Contact.setText("");
           Address.setText("");
              Status.setText("");
             
                Place.setText("");
                muni.setText("");
                street.setText("");
                Age.setText("");
                sta.setText("");
                No.setText("");
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
    if(Name.getText().isEmpty()){
           JOptionPane.showMessageDialog(this,"Table is empty and please select first");
        
    }else{
            try{
           
               Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/connector?useSSL=false","root","jayvee0123");
            String indi = Name.getText();
            String Query = "delete from new where FullName = '"+indi+"'";
                java.sql.Statement Add  = con1.createStatement();
           Add.executeUpdate(Query);
            Select();
            JOptionPane.showMessageDialog(this,"Success DELETE");
            
            }catch(Exception e){
                e.printStackTrace();
            }
        
        
    } 
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed

    }//GEN-LAST:event_AgeActionPerformed

    //for table
    private void Select(){
            DefaultTableModel tbl = (DefaultTableModel) Table1.getModel();
        try{
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/connector?useSSL=false","root","jayvee0123");
          String query = "select * from new";
        java.sql.Statement st = con.createStatement();
            ResultSet Rs = st.executeQuery(query);
       Table1.setModel(DbUtils.resultSetToTableModel(Rs));
        
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
         
        
          
        
        if(Name.getText().equals("")||Birth.getText().equals("")||Contact.getText().equals("")||Address.getText().equals("")||Status.getText().equals("")||Place.getText().equals("")||muni.getText().equals("")||street.getText().equals("")||Age.getText().equals("")||No.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Please Fill Up The Form", "Warning", JOptionPane.INFORMATION_MESSAGE);
        } else if (Integer.parseInt(Age.getText()) < 18) {
 
      JOptionPane.showMessageDialog(null, "Minor not Allowed", "Warning", JOptionPane.INFORMATION_MESSAGE);
}else{
            
            try {
                Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/connector?useSSL=false","root","jayvee0123");
           PreparedStatement Add = con1.prepareStatement("insert into new values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
            
           Add.setString(1,Name.getText());
             Add.setString(2,Birth.getText());
               Add.setString(3,Gender.getSelectedItem().toString());
             Add.setString(4,Contact.getText());
             Add.setString(5,Address.getText());
             Add.setString(6,muni.getText());
             Add.setString(7,street.getText());
             Add.setString(8,Status.getText());
             Add.setString(9,Place.getText());
             Add.setInt(10,Integer.valueOf(Age.getText()));
            Add.setString(11,sta.getText());
               Add.setString(12,Suffix.getSelectedItem().toString());
                 Add.setInt(13,Integer.valueOf(No.getText()));
               int row = Add.executeUpdate();
               JOptionPane.showMessageDialog(this,"Success upload");
               con1.close();
            Select();
            
              Name.setText("");
           Birth.setText("");
           //gender
           Contact.setText("");
           Address.setText("");
              Status.setText("");
             
                Place.setText("");
                muni.setText("");
                street.setText("");
                Age.setText("");
                sta.setText("");
                No.setText("");
            } catch (Exception e) {
               e.printStackTrace();
            }
        
        }
            
        
    }//GEN-LAST:event_jButton1ActionPerformed
//mouseClick
    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
    
          DefaultTableModel tbl = (DefaultTableModel) Table1.getModel();
        int MyIndex = Table1.getSelectedRow();
        Name.setText(tbl.getValueAt(MyIndex,0).toString());
           Birth.setText(tbl.getValueAt(MyIndex,1).toString());
            Gender.setSelectedItem(tbl.getValueAt(MyIndex,2).toString());
            Contact.setText(tbl.getValueAt(MyIndex,3).toString());
            Address.setText(tbl.getValueAt(MyIndex,4).toString());
            muni.setText(tbl.getValueAt(MyIndex,5).toString());
            street.setText(tbl.getValueAt(MyIndex,6).toString());
              Status.setText(tbl.getValueAt(MyIndex,7).toString());
             Place.setText(tbl.getValueAt(MyIndex,8).toString());
             Age.setText(tbl.getValueAt(MyIndex,9).toString());
               sta.setText(tbl.getValueAt(MyIndex,10).toString());
                Suffix.setSelectedItem(tbl.getValueAt(MyIndex,11).toString());
          No.setText(tbl.getValueAt(MyIndex,12).toString());
             
    }//GEN-LAST:event_Table1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
        try{
           
               Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/connector?useSSL=false","root","jayvee0123");
            String FullName = Name.getText();
                 
                                        
            String upQuery = "UPDATE new SET FullName='"+Name.getText()+"'"+",BirthDate='"+Birth.getText()+"'"+",Gender='"+Gender.getSelectedItem().toString()+"'"+",Contact='"+Contact.getText()+"'"+",Province='"+Address.getText()+"'"+",City_Municipality='"+muni.getText()+"'"+",House='"+street.getText()+"'"+",Citizenship='"+Status.getText()+"'"+",PlaceOfBirth='"+Place.getText()+"'"+",Civil_Status='"+sta.getText()+"'"+",Suffix='"+Suffix.getSelectedItem()+"'"+",Age='"+Age.getText()+"'"+"WHERE Rno="+No.getText();
                java.sql.Statement Add  = con1.createStatement();
           Add.executeUpdate(upQuery);
            Select();
            JOptionPane.showMessageDialog(this,"Success UPDATE");
            
            }catch(Exception e){
                e.printStackTrace();
            }
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
        new Menu().show();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NEW_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NEW_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NEW_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NEW_V.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NEW_V().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Birth;
    private javax.swing.JTextField Contact;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField No;
    private javax.swing.JTextField Place;
    private javax.swing.JTextField Status;
    private javax.swing.JComboBox<String> Suffix;
    private javax.swing.JTable Table1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField muni;
    private javax.swing.JTextField sta;
    private javax.swing.JTextField street;
    // End of variables declaration//GEN-END:variables
}
